"""
add_consumption_forecast.py
---------------------------
One-time script: merges the CNN-LSTM day-ahead consumption forecast into
matis_2025_.xlsx as a new column V (Forecast_Consumption_kW).

Source : Cons_Prediction/CNN_LSTM/Ressource/Consumption_Forecast_2025.csv
         (5-min, kW — generated by generate_consumption_forecast_2025.py)
Target : matis_2025_.xlsx  column V  (1-indexed = 22)

Run once:
  cd Optimisation
  python add_consumption_forecast.py
"""

import os
import pandas as pd
from openpyxl import load_workbook

SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
MATIS_PATH   = os.path.join(SCRIPT_DIR, 'Input', 'matis_2025_.xlsx')
FORECAST_CSV = os.path.join(SCRIPT_DIR, '..', 'Cons_Prediction', 'CNN_LSTM',
                             'Ressource', 'Consumption_Forecast_2025.csv')
NEW_COL      = 22   # Excel column V (1-indexed)


def main():
    # 1. Load the consumption forecast CSV
    print('Loading Consumption_Forecast_2025.csv ...')
    df = pd.read_csv(FORECAST_CSV)
    df['DateTime'] = pd.to_datetime(df['DateTime'])
    df = df.drop_duplicates('DateTime').sort_values('DateTime').set_index('DateTime')
    print(f'  {len(df):,} rows  |  {df.index.min().date()} -> {df.index.max().date()}')
    print(f'  Mean Forecast_Consumption_kW : {df["Forecast_Consumption_kW"].mean():.1f} kW')

    # Build lookup: "dd.mm.yyyy HH:MM:SS" -> kW value  (matches Excel DateTime format)
    forecast_map = {
        ts.strftime('%d.%m.%Y %H:%M:%S'): round(float(v), 1)
        for ts, v in zip(df.index, df['Forecast_Consumption_kW'])
    }
    print(f'  Lookup entries: {len(forecast_map):,}')

    # 2. Open matis_2025_.xlsx and write new column
    print('Opening matis_2025_.xlsx ...')
    wb = load_workbook(MATIS_PATH)
    ws = wb.active

    if ws.cell(row=1, column=NEW_COL).value is not None:
        print(f'  NOTE: column {NEW_COL} already has data — overwriting.')

    # Header rows
    ws.cell(row=1, column=NEW_COL).value = 'Forecast Consumption'
    ws.cell(row=2, column=NEW_COL).value = 'kW'
    ws.cell(row=3, column=NEW_COL).value = 'Forecast_Consumption_kW'

    # Data rows (row 4 onwards)
    print('Writing forecast data ...')
    written = missing = 0
    for r in range(4, ws.max_row + 1):
        ts_raw = ws.cell(row=r, column=1).value
        if ts_raw is None:
            continue
        ts_str = str(ts_raw).strip()
        if ts_str in forecast_map:
            ws.cell(row=r, column=NEW_COL).value = forecast_map[ts_str]
            written += 1
        else:
            missing += 1

    print(f'  Written : {written:,} rows')
    if missing:
        print(f'  Missing : {missing:,} rows (timestamps outside forecast range — left blank)')

    wb.save(MATIS_PATH)
    print(f'Saved : {MATIS_PATH}')


if __name__ == '__main__':
    main()