"""
run_optimiser.py
================
Entry point for all hydro scheduling modes.

Usage
-----
  python run_optimiser.py               # all days
  python run_optimiser.py 2025-06-15    # single day

Change MODE below to switch between models.
"""

import os
import sys
import pandas as pd

from hydro_constants import (
    DATA_FILENAME, TIMESTEP_HOURS, PEAK_TARIFF_EUR_KW,
    PEAK_TARIFF_HOUR_START, PEAK_TARIFF_HOUR_END,
    IMBALANCE_VARIANT_TAGS, DA_PRICE_VARIANT_TAGS,
    load_data, compute_seasonal_targets, compute_seasonal_production,
)

# ===========================================================================
#  SELECT MODE HERE
# ===========================================================================
#
#   'FORECAST'      Rule-based 3-state equalization (follows CNN/LSTM forecast)
#   'FORECAST_TEST' Experimental: RECOVERY → FILL_H → NORMAL state machine,
#                   peak shaving overrides all states
#   'WATER_VALUE'   LP that minimises intraday imbalance costs
#   'WATER_LEVEL'   Follows historical reference (seasonal average) production
#
MODE = 'FORECAST'  # 'FORECAST', 'FORECAST_TEST', 'WATER_VALUE', 'WATER_LEVEL'

# ---------------------------------------------------------------------------
#  IMBALANCE-PRICE FORECAST VARIANT (for value-of-information study)
# ---------------------------------------------------------------------------
#   'REAL'         Perfect foresight — uses realised BG prices (upper bound)
#   'ROLLING_MEAN' Today's 7-day rolling mean shifted 1 day forward (R^2 ~ 0.06)
#   'R2_02'        Synthetic AR(1) noise at R^2 = 0.2 (naive-statistical level)
#   'R2_05'        Synthetic AR(1) noise at R^2 = 0.5 (modern ML target)
#   'R2_08'        Synthetic AR(1) noise at R^2 = 0.8 (near-perfect)
#
# Variants are pre-generated by generate_imbalance_forecasts.py into
# Input/imbalance_forecasts.xlsx and loaded by load_data().
IMBALANCE_FORECAST = 'ROLLING_MEAN'  # 'REAL' | 'ROLLING_MEAN' | 'R2_02' | 'R2_05' | 'R2_08'

# ---------------------------------------------------------------------------
#  PRODUCTION-FORECAST SOURCE (drives Forecast_kW and the DA bid)
# ---------------------------------------------------------------------------
#   'OPERATOR'     Use the DeepNN forecast already in matis_2025_.xlsx
#                  (mimics historical operator production)
#   'LP_OPTIMISED' Override Forecast_kW with an economically optimal schedule
#                  computed daily by production_forecast_lp.py — uses yesterday's
#                  actual reservoir end levels, real inflows (perfect knowledge),
#                  forecast consumption, DA prices, rolling-mean BG forecasts,
#                  running monthly peak, and seasonal end-of-day targets.
PRODUCTION_FORECAST = 'OPERATOR'  # 'OPERATOR' | 'LP_OPTIMISED'

# ---------------------------------------------------------------------------
#  CONSUMPTION-FORECAST VARIANT (for value-of-information study on load)
# ---------------------------------------------------------------------------
#   'PERFECT'  Zero-error forecast = real consumption (theoretical upper bound)
#   'CURRENT'  Existing CNN-LSTM forecast (WMAPE ~6%)
#   'MAPE_10'  Synthetic, hour-of-day-conditional AR(1) noise at WMAPE 10%
#   'MAPE_15'  Same at WMAPE 15%
#   'MAPE_20'  Same at WMAPE 20%
# Generated by generate_consumption_forecasts.py into
# Input/consumption_forecasts.xlsx and loaded by load_data().
CONSUMPTION_FORECAST = 'CURRENT'  # 'PERFECT' | 'CURRENT' | 'MAPE_10' | 'MAPE_15' | 'MAPE_20'

# ---------------------------------------------------------------------------
#  DA-PRICE FORECAST VARIANT (for value-of-information study on day-ahead price)
# ---------------------------------------------------------------------------
#   'PERFECT'  Zero-error forecast = real DA price (theoretical upper bound)
#   'MAPE_05'  Additive AR(1) noise, MAPE ~5%  (best-in-class)
#   'MAPE_15'  Additive AR(1) noise, MAPE ~15% (2022 volatile-period equivalent)
#
# Only affects LP_OPTIMISED production forecast (production_forecast_lp.py).
# Settlement always uses the real Day_Ahead_Price_EUR_MWh column.
# Generated by generate_da_price_forecasts.py into
# Input/da_price_forecasts.xlsx and loaded by load_data().
DA_PRICE_FORECAST = 'MAPE_15'  # 'PERFECT' | 'MAPE_05' | 'MAPE_15'

# ---------------------------------------------------------------------------
#  BATTERY SETTINGS
# ---------------------------------------------------------------------------
#
#   BATTERY_ACTIVE  : True  — run battery dispatch after hydro each day
#                     False — hydro only
#   BATTERY_MODE    : 'DAY_AHEAD' — buy low / sell high on the DA market (LP)
#                     'INTRADAY'  — reservoir-triggered co-simulation (reduces intraday imbalance)
#
BATTERY_ACTIVE = False
BATTERY_MODE   = 'INTRADAY'  # 'DAY_AHEAD', 'INTRADAY'

# ---------------------------------------------------------------------------
#  FINANCIAL PARAMETERS  (battery investment analysis)
# ---------------------------------------------------------------------------
#
#   BATTERY_COST_PER_KWH   : 500 EUR/kWh  — Needs to be updated with real market data for accurate analysis.
#   BATTERY_LIFETIME_YEARS : 15 years     — assumed useful life
#   DISCOUNT_RATE          : 0.05         — 5% annual discount rate // NEEDS to be checked
#   BATTERY_DEG_PER_CYCLE  : fraction of capacity lost per full cycle
#                            e.g. 0.0001 = 0.01 %/cycle → 80 % remaining after 2 000 cycles
#   BATTERY_OM_EUR_KWH_YEAR: EUR/kWh/year — O&M cost per unit of installed capacity
#                            e.g. 8.0 EUR/kWh/year → 8000 EUR/year for a 1000 kWh battery
#
BATTERY_COST_PER_KWH    = 300.0    # EUR/kWh
BATTERY_LIFETIME_YEARS  =  15      # years
DISCOUNT_RATE           = 0.05     # —
BATTERY_DEG_PER_CYCLE   = 0.00005    # fraction/cycle  (0.005 %/cycle)
BATTERY_OM_EUR_KWH_YEAR = 8.0     # EUR/kWh/year (8 could be default)

# End-of-life: battery is considered retired at 80% remaining capacity (industry
# standard for grid-tied storage). Used to derive the LP cycle-cost penalty.
EOL_CAPACITY_FRACTION = 0.80

# Battery wear cost — marginal degradation per kWh moved through the battery
# (charge OR discharge). The WATER_VALUE LP uses this as a cycling penalty so
# it only fires the battery when the expected price spread exceeds wear cost.
# Derivation: each cycle (CAPACITY in + CAPACITY out) uses up
# BATTERY_DEG_PER_CYCLE / (1 - EOL_CAPACITY_FRACTION) of the battery's life.
# Per kWh moved through (sum of charge + discharge):
#   CYCLE_COST_EUR_KWH = BATTERY_COST_PER_KWH * BATTERY_DEG_PER_CYCLE
#                       / (2 * (1 - EOL_CAPACITY_FRACTION))
# With defaults: 300 * 0.00005 / (2 * 0.20) = 0.0375 EUR/kWh = 37.5 EUR/MWh per direction
CYCLE_COST_EUR_KWH = (BATTERY_COST_PER_KWH * BATTERY_DEG_PER_CYCLE
                      / (2.0 * (1.0 - EOL_CAPACITY_FRACTION)))

# ===========================================================================

def _make_output_filename():
    """Build a short, descriptive filename from run parameters."""
    if IMBALANCE_FORECAST not in IMBALANCE_VARIANT_TAGS:
        raise ValueError(f"Unknown IMBALANCE_FORECAST '{IMBALANCE_FORECAST}'. "
                         f"Choices: {list(IMBALANCE_VARIANT_TAGS.keys())}")
    if DA_PRICE_FORECAST not in DA_PRICE_VARIANT_TAGS:
        raise ValueError(f"Unknown DA_PRICE_FORECAST '{DA_PRICE_FORECAST}'. "
                         f"Choices: {list(DA_PRICE_VARIANT_TAGS.keys())}")
    mode_short = {'FORECAST': 'FC', 'FORECAST_TEST': 'FCT',
                  'WATER_VALUE': 'WV', 'WATER_LEVEL': 'WL'}.get(MODE, MODE)
    if not BATTERY_ACTIVE:
        batt_str = 'NoBatt'
    else:
        batt_short = {'DAY_AHEAD': 'DA', 'INTRADAY': 'ID'}.get(BATTERY_MODE, BATTERY_MODE)
        kwh = int(round(CAPACITY_KWH))
        batt_str = f'{batt_short}_{kwh}kWh'
    pf_tag = {'OPERATOR': 'PFOP', 'LP_OPTIMISED': 'PFLP'}.get(PRODUCTION_FORECAST, PRODUCTION_FORECAST)
    # DA price forecast tag only meaningful when LP_OPTIMISED; always include for traceability.
    da_tag = {'PERFECT': 'DAP', 'MAPE_05': 'DAM05', 'MAPE_15': 'DAM15'}.get(
        DA_PRICE_FORECAST, DA_PRICE_FORECAST)
    return f'{mode_short}_{batt_str}_FC{IMBALANCE_FORECAST}_{pf_tag}_LF{CONSUMPTION_FORECAST}_{da_tag}.xlsx'

# Import the correct mode module
if MODE == 'FORECAST':
    from mode_forecast import dispatch_day
elif MODE == 'FORECAST_TEST':
    from mode_forecast_test import dispatch_day
elif MODE == 'WATER_VALUE':
    from mode_water_value import dispatch_day, get_solver
elif MODE == 'WATER_LEVEL':
    from mode_water_level import dispatch_day
else:
    raise ValueError(f"Unknown MODE: '{MODE}'")

if BATTERY_ACTIVE:
    from battery_control import (
        BatteryConfig,
        dispatch_day_battery, get_battery_solver,
        SOC_INITIAL, CYCLE_KWH, CAPACITY_KWH, ROUND_TRIP_EFF, C_RATE,
        SOC_MIN, SOC_MAX, EFF_DISCHARGE, _P_MAX_BATT,
    )

if PRODUCTION_FORECAST == 'LP_OPTIMISED':
    from production_forecast_lp import (
        compute_optimal_forecast,
        get_solver as get_prod_fc_solver,
    )


def run_all(df: pd.DataFrame, target_date: str = None) -> pd.DataFrame:
    """Iterate over all days, chain reservoir levels, return full result DataFrame."""
    import datetime as _dt

    print("Computing seasonal targets...")
    season_targets    = compute_seasonal_targets(df)
    season_production = compute_seasonal_production(df) if MODE == 'WATER_LEVEL' else {}

    solver         = get_solver() if MODE == 'WATER_VALUE' else None
    batt_solver    = get_battery_solver() if BATTERY_ACTIVE else None
    prod_fc_solver = get_prod_fc_solver() if PRODUCTION_FORECAST == 'LP_OPTIMISED' else None
    prev_soc       = SOC_INITIAL if BATTERY_ACTIVE else None
    total_discharged_kwh = 0.0

    days = sorted(df['DateTime'].dt.date.unique())
    if target_date:
        days = [d for d in days if str(d) == target_date]
        if not days:
            print(f"ERROR: date '{target_date}' not found in data.")
            sys.exit(1)

    results     = []
    prev_lb     = None
    prev_lh     = None
    failed_days = 0

    # Monthly peak import state (Leistungsentgelt)
    running_peak_kW = 0.0   # highest 15-min avg import seen so far this calendar month
    current_month   = None  # track month boundary for reset

    for i, day in enumerate(days, 1):
        day_df = df[df['DateTime'].dt.date == day].copy()

        # Reset monthly peak at calendar month boundary
        if day.month != current_month:
            running_peak_kW = 0.0
            current_month   = day.month

        t_lb, t_lh = season_targets.get(day, (None, None))

        if t_lb is None: t_lb = float(day_df['Bidmi_mm'].iloc[0])
        if t_lh is None: t_lh = float(day_df['Haselholz_mm'].iloc[0])

        lb0 = prev_lb if prev_lb is not None else float(day_df['Bidmi_mm'].iloc[0])
        lh0 = prev_lh if prev_lh is not None else float(day_df['Haselholz_mm'].iloc[0])

        # Build battery config for this day (carries today's starting SOC).
        # INTRADAY battery is co-simulated inside dispatch_day.
        # DAY_AHEAD battery is fully independent → dispatch_day ignores it.
        if BATTERY_ACTIVE:
            battery_cfg = BatteryConfig(mode=BATTERY_MODE, soc0=prev_soc,
                                        cycle_cost_eur_kwh=CYCLE_COST_EUR_KWH)
        else:
            battery_cfg = None

        seas_prod = season_production.get(day) if MODE == 'WATER_LEVEL' else None

        # Day-ahead production forecast override (LP-optimised schedule).
        # Replaces Forecast_kW with the output of a midnight day-ahead LP that
        # uses yesterday's actual reservoir levels, real inflows, forecast
        # consumption, DA prices, rolling-mean BG forecasts, the running monthly
        # peak, and the seasonal end-of-day targets.
        if PRODUCTION_FORECAST == 'LP_OPTIMISED':
            optimal_fc = compute_optimal_forecast(
                day_df, lb0, lh0, t_lb, t_lh,
                running_peak_kW=running_peak_kW,
                solver=prod_fc_solver,
            )
            day_df['Forecast_kW'] = optimal_fc

        day_df = dispatch_day(
            day_df, lb0, lh0, t_lb, t_lh,
            solver=solver,
            battery_cfg=battery_cfg,
            seasonal_prod=seas_prod,
            running_peak_kW=running_peak_kW,
        )

        # Read hydro chain attributes before any reset_index can drop them
        prev_lb = getattr(day_df, '_opt_lb_end', None)
        prev_lh = getattr(day_df, '_opt_lh_end', None)
        dev_b   = getattr(day_df, '_dev_b',      float('nan'))
        dev_h   = getattr(day_df, '_dev_h',      float('nan'))

        # Battery post-dispatch
        batt_str = ""
        if BATTERY_ACTIVE:
            if BATTERY_MODE == 'INTRADAY':
                # Co-simulation already done inside dispatch_day.
                prev_soc       = getattr(day_df, '_batt_soc_end', prev_soc)
                discharged_kwh = day_df['Batt_Discharge_kW'].sum() * TIMESTEP_HOURS

            else:  # DAY_AHEAD — fully independent LP, run now
                day_df, prev_soc, discharged_kwh = dispatch_day_battery(
                    day_df, prev_soc, batt_solver, mode=BATTERY_MODE)

            total_discharged_kwh += discharged_kwh
            cycles_today = discharged_kwh / CYCLE_KWH
            batt_rev     = day_df['Batt_Revenue_EUR'].sum()
            batt_str     = f"  batt {batt_rev:+.2f} EUR  cyc {cycles_today:.2f}"

        # -----------------------------------------------------------------------
        # Grid exchange power columns
        # P_Exchange_kW > 0 → importing from grid; < 0 → exporting to grid
        # -----------------------------------------------------------------------
        batt_net = day_df['Batt_Net_kW'] if 'Batt_Net_kW' in day_df.columns else 0.0
        day_df['P_Exchange_kW'] = (
            day_df['Consumption_kW'] - day_df['Opt_M2_kW'] - day_df['Opt_M1_kW'] - batt_net
        )
        day_df['P_Import_kW'] = day_df['P_Exchange_kW'].clip(lower=0.0)

        # Hydro-only counterfactual: what the meter would show without the battery,
        # holding today's hydro dispatch fixed. Used to attribute peak-fee savings.
        day_df['P_Import_NoBatt_kW'] = (
            day_df['Consumption_kW'] - day_df['Opt_M2_kW'] - day_df['Opt_M1_kW']
        ).clip(lower=0.0)

        # Reference (historical operator) counterfactual: what the meter actually
        # showed historically. Drives the reference peak fee for comparison.
        day_df['P_Import_Ref_kW'] = (
            day_df['Consumption_kW'] - day_df['Ref_M2_kW'] - day_df['Ref_M1_kW']
        ).clip(lower=0.0)

        # Day-ahead scheduled flow (locked at midnight via the DA bid)
        # DA_Import_kW : electricity bought on the DA market (>0 when buying)
        # DA_Export_kW : electricity sold on the DA market (>0 when selling)
        # Imbalance_Import_kW : real-time deviation from the DA schedule
        #                       (>0 when more import than scheduled / less export)
        da_net = day_df['Forecast_kW'] - day_df['Forecast_Consumption_kW']
        day_df['DA_Import_kW']        = (-da_net).clip(lower=0.0)
        day_df['DA_Export_kW']        = ( da_net).clip(lower=0.0)
        day_df['Imbalance_Import_kW'] = (day_df['P_Exchange_kW'] - (-da_net)).clip(lower=0.0)

        # 15-min block average import (3 consecutive 5-min steps per block)
        N_day    = len(day_df)
        B_BLOCKS = N_day // 3

        def _avg_15min(p):
            out = []
            for b in range(B_BLOCKS):
                v = float(p[3*b] + p[3*b+1] + p[3*b+2]) / 3.0
                out.extend([v, v, v])
            rem = N_day - 3 * B_BLOCKS
            if rem > 0:
                v = float(p[3*B_BLOCKS:].mean())
                out.extend([v] * rem)
            return out

        p15_expanded        = _avg_15min(day_df['P_Import_kW'].values)
        p15_nobatt_expanded = _avg_15min(day_df['P_Import_NoBatt_kW'].values)
        p15_ref_expanded    = _avg_15min(day_df['P_Import_Ref_kW'].values)
        day_df['P_Import_15min_kW']        = p15_expanded
        day_df['P_Import_NoBatt_15min_kW'] = p15_nobatt_expanded
        day_df['P_Import_Ref_15min_kW']    = p15_ref_expanded

        # Peak-tariff time window: only blocks whose timestamps lie in
        # [PEAK_TARIFF_HOUR_START, PEAK_TARIFF_HOUR_END) count toward the bill.
        hours          = day_df['DateTime'].dt.hour.values
        in_window_mask = (hours >= PEAK_TARIFF_HOUR_START) & (hours < PEAK_TARIFF_HOUR_END)
        day_df['In_Peak_Window']                  = in_window_mask.astype(int)
        day_df['P_Import_15min_Tariff_kW']        = [p if m else 0.0
                                                      for p, m in zip(p15_expanded,        in_window_mask)]
        day_df['P_Import_NoBatt_15min_Tariff_kW'] = [p if m else 0.0
                                                      for p, m in zip(p15_nobatt_expanded, in_window_mask)]
        day_df['P_Import_Ref_15min_Tariff_kW']    = [p if m else 0.0
                                                      for p, m in zip(p15_ref_expanded,    in_window_mask)]

        # Update running monthly peak — uses the window-masked column
        day_max_peak_15min = max(day_df['P_Import_15min_Tariff_kW']) if len(day_df) else 0.0
        running_peak_kW    = max(running_peak_kW, day_max_peak_15min)

        # Console progress
        opt_profit = day_df['Opt_Energy_Trading_EUR'].sum()
        ref_profit = day_df['Ref_Energy_Trading_EUR'].sum()
        gain       = opt_profit - ref_profit
        spill      = day_df['Opt_Spill_Bidmi_kWh'].sum() + day_df['Opt_Spill_Haselholz_kWh'].sum()
        spill_str  = f"  SPILL {spill:.0f} kWh" if spill > 0.1 else ""

        print(f"[{i:3}/{len(days)}] {day}  "
              f"tgt B={t_lb:.0f} H={t_lh:.0f}  "
              f"ref {ref_profit:+.2f} EUR  opt {opt_profit:+.2f} EUR  "
              f"gain {gain:+.2f} EUR  "
              f"dLB={dev_b:+.1f}mm dLH={dev_h:+.1f}mm"
              f"{spill_str}{batt_str}"
              f"  peak {day_max_peak_15min:.0f} kW")

        failed_days += getattr(day_df, '_failed', 0)
        results.append(day_df)

    result_df = pd.concat(results, ignore_index=True)
    result_df._total_discharged_kwh  = total_discharged_kwh
    result_df._failed_days           = failed_days
    return result_df


# ---------------------------------------------------------------------------
# Output saving
# ---------------------------------------------------------------------------

def save_output(opt_df: pd.DataFrame, output_path: str):
    """Save Results + Summary sheets to Excel."""
    opt_df['Opt_Total_Energy_Cost_EUR'] = opt_df['Opt_Energy_Trading_EUR'].cumsum()

    total_ref  = opt_df['Ref_Energy_Trading_EUR'].sum()
    total_opt  = opt_df['Opt_Energy_Trading_EUR'].sum()
    total_gain = total_opt - total_ref

    # Split DA market vs ID imbalance components (both Ref and Opt).
    # Imbalance further split: long = over-delivery sold at BG_Long (positive),
    # short = under-delivery bought at BG_Short (negative). long + short = subtotal.
    total_ref_da        = opt_df['Ref_DA_EUR'].sum()
    total_ref_imb_long  = opt_df['Ref_Imbalance_Long_EUR'].sum()
    total_ref_imb_short = opt_df['Ref_Imbalance_Short_EUR'].sum()
    total_ref_imb       = opt_df['Ref_Imbalance_EUR'].sum()
    total_opt_da        = opt_df['Opt_DA_Trading_EUR'].sum()
    total_opt_imb_long  = opt_df['Opt_Imbalance_Long_EUR'].sum()
    total_opt_imb_short = opt_df['Opt_Imbalance_Short_EUR'].sum()
    total_opt_imb       = opt_df['Opt_ID_Imbalance_EUR'].sum()

    daily_ref        = opt_df.groupby(opt_df['DateTime'].dt.date)['Ref_Energy_Trading_EUR'].sum()
    daily_opt        = opt_df.groupby(opt_df['DateTime'].dt.date)['Opt_Energy_Trading_EUR'].sum()
    days_opt_better  = (daily_opt > daily_ref).sum()
    days_ref_better  = (daily_opt < daily_ref).sum()

    ref_energy_kwh = ((opt_df['Ref_M2_kW'] + opt_df['Ref_M1_kW']) * TIMESTEP_HOURS).sum()
    opt_energy_kwh = opt_df['Opt_Production_kW'].sum() * TIMESTEP_HOURS
    energy_diff    = opt_energy_kwh - ref_energy_kwh

    total_spill_b   = opt_df['Opt_Spill_Bidmi_kWh'].sum()
    total_spill_h   = opt_df['Opt_Spill_Haselholz_kWh'].sum()
    total_spill     = total_spill_b + total_spill_h

    # Monthly peak import tariff (Leistungsentgelt)
    peak_rows           = []
    total_peak_cost     = 0.0
    total_peak_cost_ref = 0.0
    peak_savings_battery = 0.0   # EUR saved by the battery on the peak fee
    if 'P_Import_15min_Tariff_kW' in opt_df.columns:
        opt_df['Month_key'] = opt_df['DateTime'].dt.to_period('M')
        # Only in-window blocks (column already masked to 0 outside the window)
        monthly_peak = opt_df.groupby('Month_key')['P_Import_15min_Tariff_kW'].max()
        monthly_cost = monthly_peak * PEAK_TARIFF_EUR_KW
        total_peak_cost = monthly_cost.sum()

        # Reference (historical operator) peak fee — what was actually paid historically
        ref_monthly_peak = None
        if 'P_Import_Ref_15min_Tariff_kW' in opt_df.columns:
            ref_monthly_peak = opt_df.groupby('Month_key')['P_Import_Ref_15min_Tariff_kW'].max()
            ref_monthly_cost = ref_monthly_peak * PEAK_TARIFF_EUR_KW
            total_peak_cost_ref = ref_monthly_cost.sum()

        # Counterfactual: what the peak fee would have been without the battery,
        # holding today's hydro dispatch fixed. Difference = battery's peak savings.
        nobatt_cost_total = 0.0
        nobatt_monthly_peak = None
        if BATTERY_ACTIVE and 'P_Import_NoBatt_15min_Tariff_kW' in opt_df.columns:
            nobatt_monthly_peak = opt_df.groupby('Month_key')['P_Import_NoBatt_15min_Tariff_kW'].max()
            nobatt_monthly_cost = nobatt_monthly_peak * PEAK_TARIFF_EUR_KW
            nobatt_cost_total   = nobatt_monthly_cost.sum()
            peak_savings_battery = nobatt_cost_total - total_peak_cost

        opt_df.drop(columns=['Month_key'], inplace=True)

        peak_rows = [('--- Grid Import Peak Tariff (Leistungsentgelt) ---', '', '')]
        for period, pk_kw, pk_eur in zip(monthly_peak.index,
                                          monthly_peak.values,
                                          monthly_cost.values):
            peak_rows.append((str(period), f'{pk_kw:.1f} kW  ->  {pk_eur:.2f}', 'EUR'))
        peak_rows += [
            ('Total peak tariff cost (Opt)', f'{total_peak_cost:,.2f}',     'EUR'),
            ('Total peak tariff cost (Ref)', f'{total_peak_cost_ref:,.2f}', 'EUR'),
            ('Tariff rate',                  f'{PEAK_TARIFF_EUR_KW:.1f}',   'EUR/kW/month'),
        ]
        if BATTERY_ACTIVE and nobatt_monthly_peak is not None:
            peak_rows += [
                ('Peak fee without battery',  f'{nobatt_cost_total:,.2f}',     'EUR'),
                ('Battery peak savings',      f'{peak_savings_battery:+,.2f}', 'EUR'),
            ]
        peak_rows.append(('', '', ''))

    # Forecast drift (FORECAST and WATER_VALUE modes)
    drift_rows = []
    if 'Forecast_Drift_kW' in opt_df.columns:
        drift     = opt_df['Forecast_Drift_kW']
        drift_kwh = (drift * TIMESTEP_HOURS).sum()
        mae_kw    = drift.abs().mean()
        n         = len(drift)
        h_below   = (drift < -1.0).sum() * TIMESTEP_HOURS
        h_above   = (drift >  1.0).sum() * TIMESTEP_HOURS
        drift_rows = [
            ('--- Forecast Drift (simulated − forecast) ---', '', ''),
            ('Cumulative drift', f'{drift_kwh:+,.0f}',  'kWh'),
            ('Mean absolute error', f'{mae_kw:.1f}',    'kW per 5-min step'),
            ('Hours below forecast', f'{h_below:.1f}',  'h  (recovery active)'),
            ('Hours above forecast', f'{h_above:.1f}',  'h'),
            ('', '', ''),
        ]

    # Battery summary
    batt_rows = []
    if BATTERY_ACTIVE and 'Batt_Revenue_EUR' in opt_df.columns:
        total_batt_rev    = opt_df['Batt_Revenue_EUR'].sum()       # ID imbalance savings
        total_discharged  = getattr(opt_df, '_total_discharged_kwh', 0.0)
        total_cycles      = total_discharged / CYCLE_KWH
        total_charged_kwh = (opt_df['Batt_Charge_kW'] * TIMESTEP_HOURS).sum()
        # Battery contribution = ID imbalance savings + peak fee savings (both EUR)
        total_batt_value  = total_batt_rev + peak_savings_battery
        # Financial analysis
        n_days              = opt_df['DateTime'].dt.date.nunique()
        batt_capex          = CAPACITY_KWH * BATTERY_COST_PER_KWH
        annual_id_revenue   = total_batt_rev       * 365.0 / n_days
        annual_peak_savings = peak_savings_battery * 365.0 / n_days
        annual_revenue      = annual_id_revenue + annual_peak_savings   # used by NPV
        annual_om           = BATTERY_OM_EUR_KWH_YEAR * CAPACITY_KWH
        annual_cf           = annual_revenue - annual_om
        annual_cycles_sim   = total_cycles * 365.0 / n_days   # annualised from simulation

        # Capacity factor in year t: linear degradation per cycle.
        # cap_factor(t) = max(0, 1 - DEG_PER_CYCLE × cumulative_cycles_at_end_of_year_t)
        # cumulative cycles at end of year t = annual_cycles × t
        def cap_factor(t):
            return max(0.0, 1.0 - BATTERY_DEG_PER_CYCLE * annual_cycles_sim * t)

        # NPV: cash flow in year t = annual_cf × cap_factor(t), discounted at DISCOUNT_RATE
        npv               = -batt_capex + sum(
                                annual_cf * cap_factor(t) / (1 + DISCOUNT_RATE) ** t
                                for t in range(1, BATTERY_LIFETIME_YEARS + 1))
        simple_payback    = (batt_capex / annual_cf) if annual_cf > 0 else float('inf')

        # Lifetime kWh discharged also degrades each year with cap_factor
        annual_discharged = total_discharged * 365.0 / n_days
        lifetime_kwh      = sum(
                                annual_discharged * cap_factor(t)
                                for t in range(1, BATTERY_LIFETIME_YEARS + 1))
        lcos              = (batt_capex / lifetime_kwh) if lifetime_kwh > 0 else float('inf')
        capacity_end_life = round(cap_factor(BATTERY_LIFETIME_YEARS) * 100, 1)

        batt_rows = [
            ('--- Battery (BESS) ---', '', ''),
            ('Mode',                  BATTERY_MODE,                    ''),
            ('Capacity',              f'{CAPACITY_KWH:.1f}',           'kWh'),
            ('Round-trip efficiency', f'{ROUND_TRIP_EFF*100:.0f}',     '%'),
            ('Total charged',         f'{total_charged_kwh:,.1f}',     'kWh'),
            ('Total discharged',      f'{total_discharged:,.1f}',      'kWh'),
            ('Total cycles',          f'{total_cycles:.1f}',           'cycles'),
            ('ID imbalance revenue',  f'{total_batt_rev:+,.2f}',       'EUR'),
            ('Peak fee savings',      f'{peak_savings_battery:+,.2f}', 'EUR'),
            ('Total battery value',   f'{total_batt_value:+,.2f}',     'EUR (ID + peak)'),
            ('', '', ''),
            ('--- Battery Investment ---', '', ''),
            ('Days simulated',        f'{n_days}',                                     'days'),
            ('Annual cycles',         f'{annual_cycles_sim:.1f}',                      'cycles/year'),
            ('Annualised ID revenue', f'{annual_id_revenue:+,.2f}',                    'EUR/year'),
            ('Annualised peak savings', f'{annual_peak_savings:+,.2f}',                'EUR/year'),
            ('Annualised total revenue', f'{annual_revenue:+,.2f}',                    'EUR/year (used in NPV)'),
            ('O&M costs',             f'{BATTERY_OM_EUR_KWH_YEAR:.1f} EUR/kWh/yr  ->  {annual_om:,.0f}',  'EUR/year'),
            ('Annual cash flow',      f'{annual_cf:+,.2f}',                            'EUR/year'),
            (f'CAPEX  ({BATTERY_COST_PER_KWH:.0f} EUR/kWh)',
                                      f'{batt_capex:,.0f}',                            'EUR'),
            (f'NPV  ({BATTERY_LIFETIME_YEARS}y, {DISCOUNT_RATE*100:.0f}%, {BATTERY_DEG_PER_CYCLE*100:.4f}%/cyc)',
                                      f'{npv:+,.0f}',                                  'EUR'),
            ('Simple payback',        f'{simple_payback:.1f}' if simple_payback < 100 else '>100',
                                                                                        'years'),
            ('LCOS',                  f'{lcos:.3f}' if lcos < 9999 else 'N/A',         'EUR/kWh cycled'),
            (f'Capacity at yr {BATTERY_LIFETIME_YEARS}',
                                      f'{capacity_end_life:.1f}',                      '%'),
            ('', '', ''),
        ]

    summary_rows = [
        ('--- Profit / Cost ---', '', ''),
        ('Reference DA',              f'{total_ref_da:+.2f}',        'EUR'),
        ('Reference Imbalance Long',  f'{total_ref_imb_long:+.2f}',  'EUR'),
        ('Reference Imbalance Short', f'{total_ref_imb_short:+.2f}', 'EUR'),
        ('Reference Imbalance',       f'{total_ref_imb:+.2f}',       'EUR'),
        ('Reference total',           f'{total_ref:+.2f}',           'EUR'),
        ('Optimised DA',              f'{total_opt_da:+.2f}',        'EUR'),
        ('Optimised Imbalance Long',  f'{total_opt_imb_long:+.2f}',  'EUR'),
        ('Optimised Imbalance Short', f'{total_opt_imb_short:+.2f}', 'EUR'),
        ('Optimised Imbalance',       f'{total_opt_imb:+.2f}',       'EUR'),
        ('Optimised total',           f'{total_opt:+.2f}',           'EUR'),
        ('Optimizer gain',            f'{total_gain:+.2f}',          'EUR'),
        ('Days opt better',           days_opt_better,                ''),
        ('Days ref better',           days_ref_better,                ''),
        ('', '', ''),
        ('--- Energy Production ---', '', ''),
        ('Reference energy',   f'{ref_energy_kwh:,.0f}',  'kWh'),
        ('Optimised energy',   f'{opt_energy_kwh:,.0f}',  'kWh'),
        ('Difference',         f'{energy_diff:+,.0f}',    'kWh'),
        ('', '', ''),
        *peak_rows,
        *drift_rows,
        ('--- Spillage Losses ---', '', ''),
        ('Bidmi spillage',     f'{total_spill_b:,.0f}',  'kWh'),
        ('Haselholz spillage', f'{total_spill_h:,.0f}',  'kWh'),
        ('Total spillage',     f'{total_spill:,.0f}',    'kWh'),
        ('', '', ''),
        *batt_rows,
        ('--- Model ---', '', ''),
        ('Mode', MODE, ''),
    ]

    summary_df = pd.DataFrame(summary_rows, columns=['Metric', 'Value', 'Unit'])

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
        opt_df.to_excel(writer, sheet_name='Results', index=False)
        summary_df.to_excel(writer, sheet_name='Summary', index=False)

    print(f"\nSaved: {output_path}")

    # ── Console summary  (subsections for readability) ──────────────────
    W = 56  # total width
    def _hdr(title):
        print(f"\n  +-- {title} " + "-" * (W - 7 - len(title)))

    print(f"\n{'='*W}")
    print(f"  Mode: {MODE}")

    _hdr("Hydro Energy Trading")
    print(f"  Reference DA      : {total_ref_da:+,.2f} EUR")
    print(f"  Reference Imb Long: {total_ref_imb_long:+,.2f} EUR")
    print(f"  Reference Imb Short:{total_ref_imb_short:+,.2f} EUR")
    print(f"  Reference Imb.    : {total_ref_imb:+,.2f} EUR")
    print(f"  Reference total   : {total_ref:+,.2f} EUR")
    print(f"  Optimised DA      : {total_opt_da:+,.2f} EUR")
    print(f"  Optimised Imb Long: {total_opt_imb_long:+,.2f} EUR")
    print(f"  Optimised Imb Short:{total_opt_imb_short:+,.2f} EUR")
    print(f"  Optimised Imb.    : {total_opt_imb:+,.2f} EUR")
    print(f"  Optimised total   : {total_opt:+,.2f} EUR")
    print(f"  Gain vs reference : {total_gain:+,.2f} EUR")

    _hdr("Production / Spill")
    print(f"  Ref energy        : {ref_energy_kwh/1000:,.1f} MWh")
    print(f"  Opt energy        : {opt_energy_kwh/1000:,.1f} MWh")
    print(f"  Total spill loss  : {total_spill/1000:,.1f} MWh")

    if drift_rows:
        _hdr("Forecast Tracking")
        print(f"  Forecast MAE      : {mae_kw:.1f} kW")
        print(f"  Cumulative drift  : {drift_kwh/1000:+,.1f} MWh")

    if peak_rows:
        _hdr("Grid Import Peak Tariff")
        print(f"  Peak fee (Ref)    : {total_peak_cost_ref:,.2f} EUR")
        print(f"  Peak fee (Opt)    : {total_peak_cost:,.2f} EUR")
        if BATTERY_ACTIVE and peak_savings_battery != 0.0:
            print(f"  Saved by battery  : {peak_savings_battery:+,.2f} EUR (vs hydro-only meter)")

    if batt_rows:
        _hdr("Battery (BESS)")
        print(f"  ID imbalance rev. : {total_batt_rev:+,.2f} EUR")
        print(f"  Peak fee savings  : {peak_savings_battery:+,.2f} EUR")
        print(f"  Total batt value  : {total_batt_value:+,.2f} EUR  ({n_days}d -> {annual_revenue:+,.0f} EUR/yr)")
        print(f"  Cycles            : {total_cycles:.1f}  ({total_discharged/1000:,.1f} MWh discharged)")

        _hdr("Battery Investment")
        print(f"  CAPEX             : {batt_capex:,.0f} EUR")
        print(f"  Annual cash flow  : {annual_cf:+,.2f} EUR/yr (incl. peak savings, after O&M)")
        print(f"  NPV ({BATTERY_LIFETIME_YEARS}y,{DISCOUNT_RATE*100:.0f}%)     : {npv:+,.0f} EUR")
        if simple_payback < 100:
            print(f"  Simple payback    : {simple_payback:.1f} years")
        else:
            print(f"  Simple payback    : >100 years")
        if lcos < 9999:
            print(f"  LCOS              : {lcos:.3f} EUR/kWh")
        else:
            print(f"  LCOS              : N/A")

    # ── Net total: hydro+battery profit, minus the peak fee actually paid ──
    if batt_rows:
        hydro_plus_batt = total_opt + total_batt_rev
        net_total       = hydro_plus_batt - total_peak_cost
        _hdr("NET TOTAL")
        print(f"  Hydro+Battery     : {hydro_plus_batt:+,.2f} EUR")
        print(f"  Peak fee          : {-total_peak_cost:+,.2f} EUR")
        print(f"  ─────────────────────────────────────")
        print(f"  NET TOTAL         : {net_total:+,.2f} EUR")
    else:
        net_total = total_opt - total_peak_cost
        _hdr("NET TOTAL")
        print(f"  Hydro profit      : {total_opt:+,.2f} EUR")
        print(f"  Peak fee          : {-total_peak_cost:+,.2f} EUR")
        print(f"  ─────────────────────────────────────")
        print(f"  NET TOTAL         : {net_total:+,.2f} EUR")

    print(f"{'='*W}")

    # Return a flat summary dict for Main_results.xlsx
    return {
        'Mode':                MODE,
        'Imbalance_Forecast':   IMBALANCE_FORECAST,
        'Production_Forecast':  PRODUCTION_FORECAST,
        'DA_Price_Forecast':    DA_PRICE_FORECAST,
        'Consumption_Forecast': CONSUMPTION_FORECAST,
        'Battery_Active':      BATTERY_ACTIVE,
        'Battery_Mode':       BATTERY_MODE            if BATTERY_ACTIVE else '-',
        'Capacity_kWh':       CAPACITY_KWH            if BATTERY_ACTIVE else 0,
        'C_Rate':             C_RATE                  if BATTERY_ACTIVE else '-',
        'RTE_pct':            round(ROUND_TRIP_EFF * 100) if BATTERY_ACTIVE else '-',
        'Deg_pct_per_cycle':  BATTERY_DEG_PER_CYCLE * 100  if BATTERY_ACTIVE else '-',
        'Lifetime_Years':     BATTERY_LIFETIME_YEARS  if BATTERY_ACTIVE else '-',
        'Discount_Rate_pct':  DISCOUNT_RATE * 100     if BATTERY_ACTIVE else '-',
        'OM_EUR_kWh_yr':      BATTERY_OM_EUR_KWH_YEAR  if BATTERY_ACTIVE else '-',
        'OM_Cost_EUR_Year':   annual_om                if batt_rows else 0,
        'Ref_DA_EUR':               round(total_ref_da,        2),
        'Ref_Imbalance_Long_EUR':   round(total_ref_imb_long,  2),
        'Ref_Imbalance_Short_EUR':  round(total_ref_imb_short, 2),
        'Ref_Imbalance_EUR':        round(total_ref_imb,       2),
        'Opt_DA_EUR':               round(total_opt_da,        2),
        'Opt_Imbalance_Long_EUR':   round(total_opt_imb_long,  2),
        'Opt_Imbalance_Short_EUR':  round(total_opt_imb_short, 2),
        'Opt_Imbalance_EUR':        round(total_opt_imb,       2),
        'Gain_EUR':                 round(total_gain,          2),
        'Days_Opt_Better': int(days_opt_better),
        'Days_Ref_Better': int(days_ref_better),
        'Opt_Energy_MWh':  round(opt_energy_kwh / 1000, 1),
        'Spill_MWh':       round(total_spill / 1000, 1),
        'Forecast_MAE_kW': round(mae_kw, 1) if drift_rows else '-',
        'Batt_Revenue_EUR':    round(total_batt_rev, 2)    if batt_rows else 0,
        'Batt_Cycles':         round(total_cycles, 1)      if batt_rows else 0,
        'Annual_Cycles':       round(annual_cycles_sim, 1) if batt_rows else 0,
        'Days_Simulated':      n_days                      if batt_rows else opt_df['DateTime'].dt.date.nunique(),
        'Annual_Revenue_EUR':  round(annual_revenue, 2)    if batt_rows else 0,
        'CAPEX_EUR':           round(batt_capex, 0)        if batt_rows else 0,
        'NPV_EUR':             round(npv, 0)               if batt_rows else 0,
        'Payback_Years':       round(simple_payback, 1)    if (batt_rows and simple_payback < 100) else ('>100' if batt_rows else 0),
        'LCOS_EUR_kWh':        round(lcos, 3)              if (batt_rows and lcos < 9999) else 0,
        'Capacity_EOL_pct':    capacity_end_life           if batt_rows else 0,
        'Peak_Tariff_EUR':         round(total_peak_cost,     2),
        'Ref_Peak_Tariff_EUR':     round(total_peak_cost_ref, 2),
        'Batt_Peak_Savings_EUR':   round(peak_savings_battery, 2) if BATTERY_ACTIVE else 0,
        'Net_Total_EUR':           round(net_total, 2),
        'Failed_Days':         getattr(opt_df, '_failed_days', 0),
        'Output_File':         os.path.basename(output_path),
    }


# ---------------------------------------------------------------------------
# Main results log  (one row per run, appended to Main_results.xlsx)
# ---------------------------------------------------------------------------

def append_main_results(output_dir: str, summary: dict):
    """Append one summary row to Output/Main_results.xlsx."""
    import datetime
    summary = {'Timestamp': datetime.datetime.now().strftime('%Y-%m-%d %H:%M'), **summary}
    row_df   = pd.DataFrame([summary])
    path     = os.path.join(output_dir, 'Main_results.xlsx')
    if os.path.exists(path):
        existing = pd.read_excel(path, engine='openpyxl')
        combined = pd.concat([existing, row_df], ignore_index=True)
    else:
        combined = row_df
    with pd.ExcelWriter(path, engine='openpyxl') as writer:
        combined.to_excel(writer, index=False)
    print(f"Main results updated: {path}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    root      = os.path.dirname(os.path.abspath(__file__))
    data_path = os.path.join(root, DATA_FILENAME)

    if not os.path.exists(data_path):
        print(f"ERROR: '{DATA_FILENAME}' not found in {root}")
        sys.exit(1)

    target_date = sys.argv[1] if len(sys.argv) > 1 else None

    print(f"Mode : {MODE}")
    print(f"Loading: {data_path}")
    print(f"Imbalance forecast variant   : {IMBALANCE_FORECAST}")
    print(f"Consumption forecast variant : {CONSUMPTION_FORECAST}")
    print(f"Production forecast source   : {PRODUCTION_FORECAST}")
    print(f"DA price forecast variant    : {DA_PRICE_FORECAST}")
    df = load_data(data_path,
                   imbalance_forecast=IMBALANCE_FORECAST,
                   consumption_forecast=CONSUMPTION_FORECAST,
                   da_price_forecast=DA_PRICE_FORECAST)
    print(f"  {len(df)} rows, {df['DateTime'].dt.date.nunique()} days")
    if target_date:
        print(f"  Single day: {target_date}")
    print()

    opt_df = run_all(df, target_date)

    output_dir  = os.path.join(root, 'Output')
    output_path = os.path.join(output_dir, _make_output_filename())
    summary     = save_output(opt_df, output_path)

    # Skip Main_results when running a single day (partial data)
    if not target_date:
        append_main_results(output_dir, summary)


if __name__ == '__main__':
    main()
